version: 2.0

jobs:
  build:
    working_directory: ~/SdkSearch

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Compile
          command: ./gradlew assemble

      - run:
          name: JVM Tests & Lint
          command: ./gradlew test :frontend:lint

      - save_cache:
          key: jars-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - run:
          name: Coalesce Test Results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp --parents {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      - store_artifacts:
          path: frontend/build/reports/lint-results.html

      - store_artifacts:
          path: frontend/build/outputs/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
