version: 2.0

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    working_directory: ~/SdkSearch

    docker:
      - image: jakewharton/sdksearch:0.0.2

    environment:
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew assemble bundle :store:item:android:assembleAndroidTest projectDependencyGraph
          # TODO remove bundle https://issuetracker.google.com/issues/79936441
          # TODO remove assembleAndroidTest https://issuetracker.google.com/issues/80464227
          # TODO remove assembleAndroidTest https://issuetracker.google.com/issues/79934948
      - store_artifacts:
          path: frontend/android/build/outputs/
      - store_artifacts:
          path: frontend/chrome-extension/build/distributions/
      - store_artifacts:
          path: frontend/web/build/distributions/
      - store_artifacts:
          path: references/legacy-printer/build/distributions/
      - store_artifacts:
          path: references/validator/build/distributions/
      - store_artifacts:
          path: build/commit-timestamp.txt
      - store_artifacts:
          path: build/project.dot.png

      - run:
          name: Test
          command: |
            ./gradlew test
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp --parents {} ~/junit/ \;
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      - run:
          name: Android Lint
          command: ./gradlew :frontend:android:lint
      - store_artifacts:
          path: frontend/android/build/reports/lint-results.html

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
